### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by snfcx** [Upsetin/ChinaUniOnline#107]
uid输入有误或网络问题...
token已更新...
Traceback (most recent call last):
  File "D:\Users\xifeng\Documents\OneDrive\桌面\ChinaUniOnline-main\main.py", line 469, in <module>
    info = GetInfo()
  File "D:\Users\xifeng\Documents\OneDrive\桌面\ChinaUniOnline-main\main.py", line 25, in GetInfo
    'authorization': 'Bearer %s' % (token),
NameError: name 'token' is not defined

进程已结束，退出代码为 1

**Comment by arenekosreal** [comment]
没有获取到token，uid检查一下是不是写对了，如果没有问题的话就等一会儿再试试。转生的账号我没有试过，请到脚本469行把info的内容给一下

**Comment by DukeWF** [comment]
这个有可能是被封了 我调试看了下 response是 '{"code": 1101, "msg": "User disabled.", "status_code": 200}'

**Comment by arenekosreal** [comment]
> 这个有可能是被封了 我调试看了下 response是 '{"code": 1101, "msg": "User disabled.", "status_code": 200}'

对。这是被封号了，可以找转生的办法，具体办法参考issue里面我发的使用提示

**Comment by Norach-I** [comment]
想问一下，GUI版目前是能正常使用嘛？

**Comment by arenekosreal** [comment]
> 想问一下，GUI版目前是能正常使用嘛？

我自己可以正常使用，不过我没有封号，不知道封号了转生的能不能也正常用

**Comment by Norach-I** [comment]
谢谢~我的还没被封号，听说用浏览器访问"https://ssxx.univs.cn/cgi-bin/authorize/token/?uid=xxxxx"获取token,refresh_token会大概率封号，一直没敢弄。。。。。。GUI版本我之前使用时，配置文件里面，字典key里面uid,token,refresh_token，对应的三个value我都填全了的。是不是只填uid对应的value，其他两个空着，也能使用？也就是这样字。

` "auth": {
        "refresh_token": "",
        "token": "",
        "uid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }`

**Comment by arenekosreal** [comment]
> 谢谢~我的还没被封号，听说用浏览器访问"https://ssxx.univs.cn/cgi-bin/authorize/token/?uid=xxxxx"获取token,refresh_token会大概率封号，一直没敢弄。。。。。。GUI版本我之前使用时，配置文件里面，字典key里面uid,token,refresh_token，对应的三个value我都填全了的。是不是只填uid对应的value，其他两个空着，也能使用？也就是这样字。
> 
> ` "auth": {
>         "refresh_token": "",
>         "token": "",
>         "uid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>     }`

对，这样也行。有uid会优先使用uid获取token

**Comment by Norach-I** [comment]
thanks~

**Comment by PODY0501** [comment]
我就是把自己的uid加到那个网址里获取token，然后就被封了，还好我们学校只交截图

**Comment by zhanghua000** [comment]
https://github.com/Upsetin/ChinaUniOnline/issues/110#issuecomment-823720580
这里我们刚刚可能找到了原因，请等待我们修复原版程序，目前只有原版程序会受到影响，因此可以使用GUI在这段时间应急
