### ISSUE TITLE
是这个 gui的问题

### ISSUE THREAD

**Issue by Philae994** [Upsetin/ChinaUniOnline#117]
# 请求帮助

## 目标

[^_^]: 在这里写你想做什么
xxxxxx
Process finished with exit code -1073740791 (0xC0000409)

**Comment by arenekosreal** [comment]
程序界面看不看得到

**Comment by arenekosreal** [comment]
有日志文件的话顺便发一下，就是程序文件夹的`logs.log`

**Comment by Philae994** [comment]
看得到 输了uid保存之后点开始 出了一会字 然后闪退
[logs.log](https://github.com/Upsetin/ChinaUniOnline/files/6362597/logs.log)
2021-04-23 11:37:09-INFO-使用网页OAuth登陆
2021-04-23 11:37:09-INFO-正在获取二维码
2021-04-23 11:37:10-ERROR-登陆出错
2021-04-23 11:37:10-INFO-使用存储的登陆信息完成登陆
2021-04-23 11:37:10-INFO-使用存储的UID完成登陆

**Comment by arenekosreal** [comment]
填写UID后保存没有？就是点一下设置界面的红色“关闭按钮”

**Comment by Philae994** [comment]
保存了 因为之前一直用着之前的gui版本 今中午用也出现这个问题 我就下了个新的 没想到新的也这样

**Comment by arenekosreal** [comment]
可以发一下调试模式的日志吗

**Comment by Philae994** [comment]
Traceback (most recent call last):
  File "C:/Users/Yinzi/Desktop/ChinaUniOnline-main_4/ChinaUniOnline-main/GUI/main-gui.py", line 948, in start
    self.processor=TestProcessor(query=self.query,show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal,user_info_signal=self.user_info_signal,update_info_signal=self.update_info_signal,prefix="ssxx")
  File "C:/Users/Yinzi/Desktop/ChinaUniOnline-main_4/ChinaUniOnline-main/GUI/main-gui.py", line 314, in __init__
    self.login()
  File "C:/Users/Yinzi/Desktop/ChinaUniOnline-main_4/ChinaUniOnline-main/GUI/main-gui.py", line 350, in login
    self.login(type_="v0")
  File "C:/Users/Yinzi/Desktop/ChinaUniOnline-main_4/ChinaUniOnline-main/GUI/main-gui.py", line 446, in login
    self.token=json_response["token"]
KeyError: 'token'
python-BaseException
 -输入·uid之后现在不出token了

**Comment by arenekosreal** [comment]
没有拿到Token，请打开脚本的调试模式，再次执行同样的操作，这时的`logs.log`文件应该有更多信息，麻烦发一下这个文件。注意：里面可能存在UID等敏感个人信息

**Comment by Philae994** [comment]
gui文件夹下的logs.log文件还是同样的内容

**Comment by arenekosreal** [comment]
改成调试模式后重启脚本才会生效，正常情况下会多出很多DEBUG等级的日志条目
