### ISSUE TITLE
不知道怎么回事

### ISSUE THREAD

**Issue by qq1050175540** [Upsetin/ChinaUniOnline#125]
# Bug报告

## 脚本类型

[^_^]:使用的是原版还是GUI版本  
原版

## 问题描述

[^_^]:遇到了什么问题
xxxx

## Python版本

[^_^]:正在使用的Python版本及架构
Python 3.8.5

## Pip安装的软件包

```text
终端执行 pip list 可查看，将内容复制替换这一行文字
 
```

## 操作系统

[^_^]:是Windows还是Linux或者OSX以及是32位系统还是64位系统
Windows

## 终端输出  

```shell

Traceback (most recent call last):
  File "D:\shuasishi\ChinaUniOnline-main\main.py", line 12, in <module>
    import requests,csv,re,json,random,time
ModuleNotFoundError: No module named 'requests'
>>> 6056dd2ca1ebb17adea1e47a
SyntaxError: invalid syntax
>>> 



```

## 日志文件

```text

Traceback (most recent call last):
  File "D:\shuasishi\ChinaUniOnline-main\main.py", line 12, in <module>
    import requests,csv,re,json,random,time
ModuleNotFoundError: No module named 'requests'
>>> 6056dd2ca1ebb17adea1e47a
SyntaxError: invalid syntax
>>> 


```

**Comment by qq1050175540** [comment]
Python 3.8.5

**Comment by arenekosreal** [comment]
安装依赖requests

**Comment by qq1050175540** [comment]
> 安装依赖要求

怎么安装呀

**Comment by qq1050175540** [comment]
main.exe 输入uid回车后闪退

**Comment by arenekosreal** [comment]
打开命令提示符，执行`pip install requests -i https://mirrors.ustc.edu.cn/pypi/web/simple`完成安装。exe已经很久没更新了

**Comment by H0121** [comment]
错误咋办
![8SB0KDZJOCF 8G4XZ7(1NMU](https://user-images.githubusercontent.com/66578388/117541240-84ab8f80-b045-11eb-8c39-672b4e4487f4.png)

**Comment by arenekosreal** [comment]
> 错误咋办
> ![8SB0KDZJOCF 8G4XZ7(1NMU](https://user-images.githubusercontent.com/66578388/117541240-84ab8f80-b045-11eb-8c39-672b4e4487f4.png)

pycharm运行这玩意容易出现各种问题，试试直接在终端里面运行

**Comment by H0121** [comment]
> > 错误咋办
> > ![8SB0KDZJOCF 8G4XZ7(1NMU](https://user-images.githubusercontent.com/66578388/117541240-84ab8f80-b045-11eb-8c39-672b4e4487f4.png)
> 
> pycharm运行这玩意容易出现各种问题，试试直接在终端里面运行

终端也是同样的问题
![SR`I{CFOO XX}D(T_S@CEDC](https://user-images.githubusercontent.com/66578388/117558428-fb7d7280-b0af-11eb-8319-4e74d7d6ec61.png)

**Comment by arenekosreal** [comment]
手动到脚本382行下面加一行`print(a.text)`，启动脚本之后多出来的输出就是a的内容，麻烦把a的内容发一下

**Comment by H0121** [comment]
> 手动到脚本382行下面加一行`print(a.text)`，启动脚本之后多出来的输出就是a的内容，麻烦把a的内容发一下
这个？
![A$E_`7W{ JL2VFICC04_ ZW](https://user-images.githubusercontent.com/66578388/117559256-4ef2bf00-b0b6-11eb-8f7e-5db02f303b22.png)

**Comment by arenekosreal** [comment]
> > 手动到脚本382行下面加一行`print(a.text)`，启动脚本之后多出来的输出就是a的内容，麻烦把a的内容发一下
> 这个？
> ![A$E_`7W{ JL2VFICC04_ ZW](https://user-images.githubusercontent.com/66578388/117559256-4ef2bf00-b0b6-11eb-8f7e-5db02f303b22.png)
> 
> 

对的，从内容来看，你这号被封了，现在微信应该也不能用了，在 https://github.com/Upsetin/ChinaUniOnline/issues/106 里面找找创新号的办法吧

**Comment by qq1050175540** [comment]
怎么从终端运行啊

**Comment by arenekosreal** [comment]
> 怎么从终端运行啊

看上面的内容，大概就是打开命令提示符，切换工作目录到脚本文件夹，使用python运行脚本
