### ISSUE TITLE
无法获取token | uid输入有误或网络问题

### ISSUE THREAD

**Issue by xlc520** [Upsetin/ChinaUniOnline#130]
# Bug报告

## 脚本类型
控制台，非GUI

## 问题描述
uid输入有误或网络问题

## Python版本

3.6.8

## Pip安装的软件包

依赖已安装

## 操作系统
Windows 64位系统

## 终端输出  

```shell
正在获取token，请稍后...
uid输入有误或网络问题...
token已更新...
Traceback (most recent call last):
  File "main.py", line 472, in <module>
    info = GetInfo()
  File "main.py", line 25, in GetInfo
    'authorization': 'Bearer %s' % (token),
NameError: name 'token' is not defined

```

### 接口返回信息
接口：https://ssxx.univs.cn/cgi-bin/authorize/token/?t=1621853396&uid=xxxx

```shell
{"code": 1102, "msg": "User name or password is missing.", "status_code": 200}
```
可能是换接口了

**Comment by arenekosreal** [comment]
GUI版本已更新，如果足够稳定，将合并新的登陆方式进原版脚本。麻烦使用GUI版本测试一下

**Comment by xlc520** [comment]
日志如下，必须抓uc_token吗，这样有点麻烦，如果直接使用抓取token也可以用
如果uc_token不会变倒是可以
```shell
2021-05-24 21:18:49-INFO-使用网页OAuth登陆
2021-05-24 21:18:49-INFO-正在获取二维码
2021-05-24 21:18:50-ERROR-登陆出错
2021-05-24 21:18:50-INFO-使用存储的登陆信息完成登陆
2021-05-24 21:18:50-ERROR-uc_token未设置
```

**Comment by arenekosreal** [comment]
已发布修改，现在登陆信息检查顺序为uc_token>token>uid
请到我的同名仓库看一下问题是否解决
另外从解码结果来看uc_token的有效期是15天，比token更长

**Comment by xlc520** [comment]
### 1.uid登录，到`使用存储的UID完成登陆`窗口就自动退出
```shell
2021-05-24 22:30:50-INFO-使用网页OAuth登陆
2021-05-24 22:30:50-INFO-正在获取二维码
2021-05-24 22:30:50-ERROR-登陆出错
2021-05-24 22:30:50-INFO-使用存储的登陆信息完成登陆
2021-05-24 22:30:50-ERROR-未设置uc_token
2021-05-24 22:30:50-ERROR-Token未设置
2021-05-24 22:30:50-INFO-使用存储的UID完成登陆
```
 这是我用cmd运行，打印的日志
```shell
Traceback (most recent call last):
  File ".\main-gui.py", line 974, in start
    self.processor=TestProcessor(query=self.query,show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal,user_info_signal=self.user_info_signal,update_info_signal=self.update_info_signal,prefix="ssxx")
  File ".\main-gui.py", line 314, in __init__
    self.login()
  File ".\main-gui.py", line 350, in login
    self.login(type_="v0")
  File ".\main-gui.py", line 471, in login
    self.token=json_response["token"]
KeyError: 'token'
 ```

### 2.使用存储的uc_token登录，日志如下
```shell
2021-05-24 22:34:21-INFO-使用网页OAuth登陆
2021-05-24 22:34:21-INFO-正在获取二维码
2021-05-24 22:34:22-ERROR-登陆出错
2021-05-24 22:34:22-INFO-使用存储的登陆信息完成登陆
2021-05-24 22:34:22-INFO-使用存储的uc_token完成登陆
2021-05-24 22:34:22-INFO-用户 来自 ，手机号 +86 
2021-05-24 22:34:23-INFO-已准备处理四史学习内容
2021-05-24 22:34:23-INFO-正在处理第 1 次的 限时赛

Traceback (most recent call last):
  File ".\main-gui.py", line 1564, in user_info_callback
    self.avatar=UserAvatar(parent=self,name=info["name"],phone=info["phone"],score=info["integral"],times=info["join_times"],t_score=info["t_integral"],t_times=info["t_join_times"],school=info["university_name"],avatar=self.draw_pic(data=info["avatar"]),province_name=info["province_name"])
  File ".\main-gui.py", line 1599, in draw_pic
    plt.legend(loc="best",prop=self.font_prop)
  File "D:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2691, in legend
    return gca().legend(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 406, in legend
    self.legend_ = mlegend.Legend(self, handles, labels, **kwargs)
  File "D:\Anaconda3\lib\site-packages\matplotlib\legend.py", line 436, in __init__
    self._fontsize = self.prop.get_size_in_points()
AttributeError: 'str' object has no attribute 'get_size_in_points'
```

**Comment by arenekosreal** [comment]
UID登陆已经被官方关闭了，现在能用的就token和uc_token两种登陆方式
第二个问题是我写的时候没有写标准的问题，在原版Python里面没有问题，所以就没有发现。已进行修改
已存在的配置文件需要手动修改，用文本编辑器打开`config.json`，找到`font_prop`项，将原本的值`SimSun`改成`{"family":"SimSun"}`

**Comment by xlc520** [comment]
控制台的换两个参数，使用uc_token，也可以用，昨天获取的uc-token，今天没失效，应该就是15天左右有效期。
