### ISSUE TITLE
执行后没反应

### ISSUE THREAD

**Issue by daizixiang666** [Upsetin/ChinaUniOnline#135]
# 请求帮助
前几个版本设置好双击都可以执行，昨天更新的双击后无法执行，不显示GUI页面
## 目标
程序运行
[^_^]: 在这里写你想做什么
直接双击后无法执行，所以用了IDEL，依赖已经安装，python版本3.6.3.报错如下
Traceback (most recent call last):
  File "C:\Users\花花花\Desktop\ChinaUniOnline-main(5)\ChinaUniOnline-main\GUI\11.py", line 1847, in <module>
    ui=UI()
  File "C:\Users\花花花\Desktop\ChinaUniOnline-main(5)\ChinaUniOnline-main\GUI\11.py", line 1475, in __init__
    self.setWindowFlag(Qt.WindowType.FramelessWindowHint)
AttributeError: type object 'Qt' has no attribute 'WindowType'

**Comment by arenekosreal** [comment]
https://github.com/Upsetin/ChinaUniOnline/issues/132#issuecomment-847051404
请按照这里面的方法更新PyQt6到最新版本

**Comment by daizixiang666** [comment]
解决了，谢谢了

**Comment by arenekosreal** [comment]
解决了麻烦点一下Close issue关闭这个问题
