### ISSUE TITLE
软件不行了，好像是认证方式改了

### ISSUE THREAD

**Issue by Graphite-core** [Upsetin/ChinaUniOnline#24]

**Comment by LRSnowX** [comment]
正在获取登陆二维码...
请用微信扫描二维码登陆...
Traceback (most recent call last):
  File "/Users/shibu/Downloads/ChinaUniOnline-main/main.py", line 434, in <module>
    Login()
  File "/Users/shibu/Downloads/ChinaUniOnline-main/main.py", line 349, in Login
    ViewQR(a.json()['data']['qrcode'])
TypeError: 'NoneType' object is not subscriptable

今天开始打开一直是这样了

**Comment by Graphite-core** [comment]
> 正在获取登陆二维码...
> 请用微信扫描二维码登陆...
> Traceback (most recent call last):
> File "/Users/shibu/Downloads/ChinaUniOnline-main/main.py", line 434, in
> Login()
> File "/Users/shibu/Downloads/ChinaUniOnline-main/main.py", line 349, in Login
> ViewQR(a.json()['data']['qrcode'])
> TypeError: 'NoneType' object is not subscriptable
> 
> 今天开始打开一直是这样了

大学生在线网页登录崩了，没法获取二维码

**Comment by arenekosreal** [comment]
服务器关闭网页答题了，用新版GUI程序，终端程序等dalao更新
