### ISSUE TITLE
会闪退

### ISSUE THREAD

**Issue by Belovedcc** [Upsetin/ChinaUniOnline#33]
![image](https://user-images.githubusercontent.com/42835451/111284624-4021fa00-867b-11eb-8e7b-3cfd008639be.png)
请问这是什么意思？出现这种问题之后就闪退了
![image](https://user-images.githubusercontent.com/42835451/111284801-6cd61180-867b-11eb-8118-13fbf0791708.png)
这是控制台

**Comment by arenekosreal** [comment]
是否设置了UID或者Token用作登陆认证信息？

**Comment by Belovedcc** [comment]
> 是否设置了UID或者Token用作登陆认证信息？

![image](https://user-images.githubusercontent.com/42835451/111312989-d1549900-869a-11eb-9177-ef533f12dc64.png)
是这样吗

![QQ图片20210316210533](https://user-images.githubusercontent.com/42835451/111313476-5dff5700-869b-11eb-8bc6-4e3d24e993b1.png)

还是出现这个之后就闪退

**Comment by arenekosreal** [comment]
应该是这样，可以在设置里面把调试模式打开或者手动编辑配置文件把debug的值改成true再执行一下程序让我看看日志输出吗

**Comment by xlc520** [comment]
运行后点击设置会报错
Traceback (most recent call last):
  File "main-gui.py", line 1048, in setting_callback
    setting=SettingWindow(parent=self,theme=self.theme.setting)
File "main-gui.py", line 645, in __init__
  uid_input.setText(self.conf["auth"]["uid"])

另外，作者可以弄一个控制台的嘛，参数直接设置在代码或者配置文件里

**Comment by arenekosreal** [comment]
看看设置文件config.json里面auth小节是不是没有uid这一项，没有的话加一下，值是空字符串或者抓包捕获的uid值，下载最新的程序应该可以实现自动更新旧版配置文件了。控制台的程序就是dalao原版程序，麻烦等一下他更新

**Comment by xlc520** [comment]
> 看看设置文件config.json里面auth小节是不是没有uid这一项，没有的话加一下，值是空字符串或者抓包捕获的uid值，下载最新的程序应该可以实现自动更新旧版配置文件了。控制台的程序就是dalao原版程序，麻烦等一下他更新

更简的方法，删除config.json重新运行

**Comment by Belovedcc** [comment]
> 应该是这样，可以在设置里面把调试模式打开或者手动编辑配置文件把debug的值改成true再执行一下程序让我看看日志输出吗

2021-03-17 21:13:50-DEBUG-当前调试状态：True，使用样式：默认，完成UI初始化
2021-03-17 21:13:50-DEBUG-正在尝试更新旧版配置
2021-03-17 21:13:50-DEBUG-正在比较键值 debug
2021-03-17 21:13:50-DEBUG-无需更新键值 debug 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 proxy
2021-03-17 21:13:50-DEBUG-无需更新键值 proxy 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 theme
2021-03-17 21:13:50-DEBUG-无需更新键值 theme 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 way
2021-03-17 21:13:50-DEBUG-无需更新键值 way 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 hide
2021-03-17 21:13:50-DEBUG-无需更新键值 hide 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 auth
2021-03-17 21:13:50-DEBUG-无需更新键值 auth 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 hero
2021-03-17 21:13:50-DEBUG-无需更新键值 hero 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 revival
2021-03-17 21:13:50-DEBUG-无需更新键值 revival 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 creation
2021-03-17 21:13:50-DEBUG-无需更新键值 creation 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 belief
2021-03-17 21:13:50-DEBUG-无需更新键值 belief 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 limit_time
2021-03-17 21:13:50-DEBUG-无需更新键值 limit_time 的数据
2021-03-17 21:13:50-DEBUG-正在比较键值 rob
2021-03-17 21:13:50-DEBUG-无需更新键值 rob 的数据
2021-03-17 21:13:50-DEBUG-更新后的配置：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
2021-03-17 21:13:52-DEBUG-初始化设置界面。设置内容：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
2021-03-17 21:13:52-DEBUG-最后的元素位置：(1,3)
2021-03-17 21:13:54-DEBUG-正在启动子线程
2021-03-17 21:13:54-INFO-使用网页OAuth登陆
2021-03-17 21:13:54-DEBUG-random=HO9BwGm6rtduXKzeSnZh
2021-03-17 21:13:54-INFO-正在获取二维码
2021-03-17 21:13:54-DEBUG-response={'data': None, 'code': 500, 'message': '获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。'}
2021-03-17 21:13:54-ERROR-登陆出错
2021-03-17 21:13:54-DEBUG-获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。
2021-03-17 21:13:54-INFO-使用存储的登陆信息完成登陆
2021-03-17 21:13:54-DEBUG-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764,refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ,uid=
2021-03-17 21:13:54-DEBUG-未设置UID，使用存储的Token
2021-03-17 21:13:54-DEBUG-Token分片：eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
2021-03-17 21:13:54-DEBUG-分片解码完成
2021-03-17 21:13:54-DEBUG-Token分片：eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ
2021-03-17 21:13:54-DEBUG-分片解码完成
2021-03-17 21:13:54-DEBUG-Token分片：2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764
2021-03-17 21:13:54-DEBUG-跳过分片解码
2021-03-17 21:13:54-DEBUG-返回数据：{'status_code': 403, 'code': 2, 'message': "No 'Authorization' in request headers."}
2021-03-17 21:13:54-ERROR-更新Token失败,服务器返回信息：No 'Authorization' in request headers.
2021-03-17 21:13:54-ERROR-Token已过期

**Comment by arenekosreal** [comment]
> > 应该是这样，可以在设置里面把调试模式打开或者手动编辑配置文件把debug的值改成true再执行一下程序让我看看日志输出吗
> 
> 2021-03-17 21:13:50-DEBUG-当前调试状态：True，使用样式：默认，完成UI初始化
> 2021-03-17 21:13:50-DEBUG-正在尝试更新旧版配置
> 2021-03-17 21:13:50-DEBUG-正在比较键值 debug
> 2021-03-17 21:13:50-DEBUG-无需更新键值 debug 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 proxy
> 2021-03-17 21:13:50-DEBUG-无需更新键值 proxy 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 theme
> 2021-03-17 21:13:50-DEBUG-无需更新键值 theme 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 way
> 2021-03-17 21:13:50-DEBUG-无需更新键值 way 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 hide
> 2021-03-17 21:13:50-DEBUG-无需更新键值 hide 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 auth
> 2021-03-17 21:13:50-DEBUG-无需更新键值 auth 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 hero
> 2021-03-17 21:13:50-DEBUG-无需更新键值 hero 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 revival
> 2021-03-17 21:13:50-DEBUG-无需更新键值 revival 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 creation
> 2021-03-17 21:13:50-DEBUG-无需更新键值 creation 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 belief
> 2021-03-17 21:13:50-DEBUG-无需更新键值 belief 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 limit_time
> 2021-03-17 21:13:50-DEBUG-无需更新键值 limit_time 的数据
> 2021-03-17 21:13:50-DEBUG-正在比较键值 rob
> 2021-03-17 21:13:50-DEBUG-无需更新键值 rob 的数据
> 2021-03-17 21:13:50-DEBUG-更新后的配置：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
> 2021-03-17 21:13:52-DEBUG-初始化设置界面。设置内容：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
> 2021-03-17 21:13:52-DEBUG-最后的元素位置：(1,3)
> 2021-03-17 21:13:54-DEBUG-正在启动子线程
> 2021-03-17 21:13:54-INFO-使用网页OAuth登陆
> 2021-03-17 21:13:54-DEBUG-random=HO9BwGm6rtduXKzeSnZh
> 2021-03-17 21:13:54-INFO-正在获取二维码
> 2021-03-17 21:13:54-DEBUG-response={'data': None, 'code': 500, 'message': '获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。'}
> 2021-03-17 21:13:54-ERROR-登陆出错
> 2021-03-17 21:13:54-DEBUG-获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。
> 2021-03-17 21:13:54-INFO-使用存储的登陆信息完成登陆
> 2021-03-17 21:13:54-DEBUG-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764,refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ,uid=
> 2021-03-17 21:13:54-DEBUG-未设置UID，使用存储的Token
> 2021-03-17 21:13:54-DEBUG-Token分片：eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
> 2021-03-17 21:13:54-DEBUG-分片解码完成
> 2021-03-17 21:13:54-DEBUG-Token分片：eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ
> 2021-03-17 21:13:54-DEBUG-分片解码完成
> 2021-03-17 21:13:54-DEBUG-Token分片：2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764
> 2021-03-17 21:13:54-DEBUG-跳过分片解码
> 2021-03-17 21:13:54-DEBUG-返回数据：{'status_code': 403, 'code': 2, 'message': "No 'Authorization' in request headers."}
> 2021-03-17 21:13:54-ERROR-更新Token失败,服务器返回信息：No 'Authorization' in request headers.
> 2021-03-17 21:13:54-ERROR-Token已过期

试一下把login()函数中的
```python
        if self.expire-time.time()<500:
            self.update_token()
```
这一部分移动到
```python
        self.session.headers.update(orig_headers)
        self.session.headers.update(headers)
```
之后
整个部分变成
![image](https://user-images.githubusercontent.com/17194552/111476399-16470100-8769-11eb-8e66-4b16bb1d83f8.png)
这样试一下
而且日志里面看Token已经过期了，token的有效期挺短的，建议重新抓包获取一个新token或者直接使用UID登陆，UID目前测试来看是长期有效的

**Comment by Belovedcc** [comment]
> > > 应该是这样，可以在设置里面把调试模式打开或者手动编辑配置文件把debug的值改成true再执行一下程序让我看看日志输出吗
> > 
> > 
> > 2021-03-17 21:13:50-DEBUG-当前调试状态：True，使用样式：默认，完成UI初始化
> > 2021-03-17 21:13:50-DEBUG-正在尝试更新旧版配置
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 debug
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 debug 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 proxy
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 proxy 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 theme
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 theme 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 way
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 way 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 hide
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 hide 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 auth
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 auth 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 hero
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 hero 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 revival
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 revival 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 creation
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 creation 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 belief
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 belief 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 limit_time
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 limit_time 的数据
> > 2021-03-17 21:13:50-DEBUG-正在比较键值 rob
> > 2021-03-17 21:13:50-DEBUG-无需更新键值 rob 的数据
> > 2021-03-17 21:13:50-DEBUG-更新后的配置：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
> > 2021-03-17 21:13:52-DEBUG-初始化设置界面。设置内容：{'auth': {'refresh_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ', 'token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764', 'uid': ''}, 'belief': {'enabled': True, 'times': 1, 'title': '信念篇'}, 'creation': {'enabled': True, 'times': 1, 'title': '创新篇'}, 'debug': True, 'hero': {'enabled': True, 'times': 1, 'title': '英雄篇'}, 'hide': False, 'limit_time': {'enabled': True, 'times': 1, 'title': '限时赛'}, 'proxy': '', 'revival': {'enabled': True, 'times': 1, 'title': '复兴篇'}, 'rob': {'enabled': True, 'times': 1, 'title': '抢十赛'}, 'theme': 'default', 'way': 1}
> > 2021-03-17 21:13:52-DEBUG-最后的元素位置：(1,3)
> > 2021-03-17 21:13:54-DEBUG-正在启动子线程
> > 2021-03-17 21:13:54-INFO-使用网页OAuth登陆
> > 2021-03-17 21:13:54-DEBUG-random=HO9BwGm6rtduXKzeSnZh
> > 2021-03-17 21:13:54-INFO-正在获取二维码
> > 2021-03-17 21:13:54-DEBUG-response={'data': None, 'code': 500, 'message': '获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。'}
> > 2021-03-17 21:13:54-ERROR-登陆出错
> > 2021-03-17 21:13:54-DEBUG-获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。
> > 2021-03-17 21:13:54-INFO-使用存储的登陆信息完成登陆
> > 2021-03-17 21:13:54-DEBUG-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764,refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTU5MDk5NTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImlzX3BlcmZlY3QiOnRydWV9.vB1A-dc1t2sZ7VpXd9YfK9_TsesfwpvFblI_70h13nQ,uid=
> > 2021-03-17 21:13:54-DEBUG-未设置UID，使用存储的Token
> > 2021-03-17 21:13:54-DEBUG-Token分片：eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
> > 2021-03-17 21:13:54-DEBUG-分片解码完成
> > 2021-03-17 21:13:54-DEBUG-Token分片：eyJleHAiOjE2MTU4OTkxNTIsImlhdCI6MTYxNTg4ODM1MiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNTg4ODM1MiwidWlkIjoiNjAzNmYxNmY1MmU3MjE4ZWI0NDQ2MDc2IiwibmFtZSI6Ilx1N2EwYlx1NWZlMFx1NzQyYSIsImNvZGUiOiI2MDM2ZjE2ZjUyZTcyMThlYjQ0NDYwNzYiLCJpc19wZXJmZWN0Ijp0cnVlfQ
> > 2021-03-17 21:13:54-DEBUG-分片解码完成
> > 2021-03-17 21:13:54-DEBUG-Token分片：2ZK6v2SaEgwlvVgSEoofHowlDoOcw0gSGvfy1wga764
> > 2021-03-17 21:13:54-DEBUG-跳过分片解码
> > 2021-03-17 21:13:54-DEBUG-返回数据：{'status_code': 403, 'code': 2, 'message': "No 'Authorization' in request headers."}
> > 2021-03-17 21:13:54-ERROR-更新Token失败,服务器返回信息：No 'Authorization' in request headers.
> > 2021-03-17 21:13:54-ERROR-Token已过期
> 
> 试一下把login()函数中的
> 
> ```python
>         if self.expire-time.time()<500:
>             self.update_token()
> ```
> 
> 这一部分移动到
> 
> ```python
>         self.session.headers.update(orig_headers)
>         self.session.headers.update(headers)
> ```
> 
> 之后
> 整个部分变成
> ![image](https://user-images.githubusercontent.com/17194552/111476399-16470100-8769-11eb-8e66-4b16bb1d83f8.png)
> 这样试一下
> 而且日志里面看Token已经过期了，token的有效期挺短的，建议重新抓包获取一个新token或者直接使用UID登陆，UID目前测试来看是长期有效的

感谢老哥 UID成功了  非常感谢

**Comment by arenekosreal** [comment]
解决了问题请点一下Close issue关闭这一项问题，谢谢
