### ISSUE TITLE
用的GUI版本也是闪退 

### ISSUE THREAD

**Issue by Philae994** [Upsetin/ChinaUniOnline#38]
在程序里输入token refreshtoken 之后就闪退了

**Comment by arenekosreal** [comment]
麻烦给一下终端输出

**Comment by panserQ** [comment]
我也是这样的
Process finished with exit code -1073740791 (0xC0000409)

**Comment by Philae994** [comment]
Process finished with exit code -1073740791 (0xC0000409)

**Comment by arenekosreal** [comment]
发一下日志和终端输出，光说这个只有老天爷才知道发生了什么😂

**Comment by Philae994** [comment]
Traceback (most recent call last):
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 533, in start
    self.processor=TestProcessor(show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal)
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 83, in __init__
    self.login()
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 108, in login
    json_response=self.session.get("https://oauth.u.hep.com.cn/oauth/wxapp/qrcode/%s" %self.client,params=params).json()
  File "E:\Python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname


我debug在997行出错       raise ValueError("check_hostname requires server_hostname")

**Comment by arenekosreal** [comment]
网上这个

> Traceback (most recent call last):
> File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 533, in start
> self.processor=TestProcessor(show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal)
> File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 83, in **init**
> self.login()
> File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main/GUI/main-gui.py", line 108, in login
> json_response=self.session.get("https://oauth.u.hep.com.cn/oauth/wxapp/qrcode/%s" %self.client,params=params).json()
> File "E:\Python\lib\site-packages\requests\sessions.py", line 555, in get
> return self.request('GET', url, **kwargs)
> File "E:\Python\lib\site-packages\requests\sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "E:\Python\lib\site-packages\requests\sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "E:\Python\lib\site-packages\requests\adapters.py", line 439, in send
> resp = conn.urlopen(
> File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
> self._prepare_proxy(conn)
> File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
> conn.connect()
> File "E:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
> conn = self._connect_tls_proxy(hostname, conn)
> File "E:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy return ssl_wrap_socket( File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
> ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls) File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
> return ssl_context.wrap_socket(sock)
> File "E:\Python\lib\ssl.py", line 500, in wrap_socket
> return self.sslsocket_class._create(
> File "E:\Python\lib\ssl.py", line 997, in _create
> raise ValueError("check_hostname requires server_hostname")
> ValueError: check_hostname requires server_hostname
> 
> 我debug在997行出错 raise ValueError("check_hostname requires server_hostname")

网上这个问题都是urllib3的问题，并且已经在新版本修复。请确认python和相关第三方库的版本足够高，目前最新的Python是3.9.2，requests的最新版是2.25.1，兼容requests的urllib3的最新版本是1.26.4
如果还是不能解决问题，请使用最新版的脚本在设置里面打开调试模式并将日志文件发上来让我看一下。

**Comment by BaiYunFeii** [comment]
2021-03-18 03:16:05-INFO-使用网页OAuth登陆
2021-03-18 03:16:05-INFO-正在获取二维码
2021-03-18 03:16:05-ERROR-登陆出错
2021-03-18 03:16:05-INFO-使用存储的登陆信息完成登陆
2021-03-18 03:16:05-ERROR-Token未设置
直接闪退

**Comment by Philae994** [comment]
填完token要点击左上角保存一下 问题已解决 感谢大佬

**Comment by arenekosreal** [comment]
> 2021-03-18 03:16:05-INFO-使用网页OAuth登陆
> 2021-03-18 03:16:05-INFO-正在获取二维码
> 2021-03-18 03:16:05-ERROR-登陆出错
> 2021-03-18 03:16:05-INFO-使用存储的登陆信息完成登陆
> 2021-03-18 03:16:05-ERROR-Token未设置
> 直接闪退

就是字面意思，没有写Token，现在登陆需要Token或者UID，有UID的情况下程序会优先使用UID获取Token

**Comment by arenekosreal** [comment]
登陆信息写进去了要点一下设置左上角的“关闭”才会保存😂
也许我应该加一个提示的
如果解决了问题，请点一下Close issue关闭这个问题

**Comment by Philae994** [comment]
中午尝试正常刷了一次 之后又闪退了
哎 好辛苦 对 中午我点击左上角刷了 然后又不行了
Traceback (most recent call last):
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main_2/ChinaUniOnline-main/GUI/main-gui.py", line 536, in start
    self.processor=TestProcessor(show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal)
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main_2/ChinaUniOnline-main/GUI/main-gui.py", line 86, in __init__
    self.login()
  File "C:/Users/Yinzi/Downloads/Compressed/ChinaUniOnline-main_2/ChinaUniOnline-main/GUI/main-gui.py", line 111, in login
    json_response=self.session.get("https://oauth.u.hep.com.cn/oauth/wxapp/qrcode/%s" %self.client,params=params).json()
  File "E:\Python\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "E:\Python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "E:\Python\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "E:\Python\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "E:\Python\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "E:\Python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Python\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by Philae994** [comment]
辛苦巨佬

**Comment by arenekosreal** [comment]
这个似乎一直都是网络问题或者Python版本过低导致的，考虑到你有过正常的经历，当出现问题的时候你的电脑可以访问  https://oauth.u.hep.com.cn 吗？只要出一个网页就行 
如果网页正常而程序还有问题，请尝试执行`pip install urllib3==1.25.7`降级urllib3

**Comment by Philae994** [comment]
降级之后可以了 感谢
