### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhtok** [Upsetin/ChinaUniOnline#45]
# Bug报告

## 脚本类型

GUI

## 问题描述

无法使用，点击开始后界面闪退然后终端输出错误

## 终端输出  

```shell

C:\Users\Chris\Desktop\ChinaUniOnline-main\GUI>python main-gui.py
Traceback (most recent call last):
  File "C:\Users\Chris\Desktop\ChinaUniOnline-main\GUI\main-gui.py", line 536, in start
    self.processor=TestProcessor(show_qr_signal=self.show_qr_signal,close_qr_signal=self.close_qr_signal)
  File "C:\Users\Chris\Desktop\ChinaUniOnline-main\GUI\main-gui.py", line 86, in __init__
    self.login()
  File "C:\Users\Chris\Desktop\ChinaUniOnline-main\GUI\main-gui.py", line 116, in login
    self.login(type_="v0")
  File "C:\Users\Chris\Desktop\ChinaUniOnline-main\GUI\main-gui.py", line 213, in login
    self.expire=self.decode_token()[self.token.split(".")[1]]["exp"]
IndexError: list index out of range


```

## 日志文件

```text

没有log。

```

**Comment by arenekosreal** [comment]
登陆Token不对，它的模式应该是三个字符串用“.”连接起来组合成的一个超长字符串，log可以在脚本文件夹下那个`logs.log`文件里面找到，设置里面打开调试模式后日志数据更有价值

**Comment by arenekosreal** [comment]
如果解决了问题，请点一下Close issue关闭这项问题

**Comment by zhtok** [comment]
> 如果解决了问题，请点一下Close issue关闭这项问题

thx~
