### ISSUE TITLE
GUI问题

### ISSUE THREAD

**Issue by BiiiGerrr** [Upsetin/ChinaUniOnline#70]
抢十赛 
Traceback (most recent call last):
  File "main-gui.py", line 705, in start
    self.processor.start(tray=self.tray)
  File "main-gui.py", line 379, in start
    self.process(mode_id=key,sleep=sleepflag)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 367, in iter
    return fut.result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "main-gui.py", line 417, in process
    self.logger.error("服务器返回错误代码：%d，错误信息：%s" %(json_response["code"],json_response["message"]))
KeyError: 'message'

**Comment by arenekosreal** [comment]
现在已经修复不能显示错误信息的问题，麻烦再给一下终端输出和调试模式的日志文件`logs.log`😂

**Comment by BiiiGerrr** [comment]
2021-03-26 19:09:47-DEBUG-已提交用户数据
2021-03-26 19:09:47-DEBUG-获取数据：{'integral': 2757, 'join_times': 217, 't_join_times': 0, 't_integral': 0, 'university_name': '郑州大学', 'avatar': [{'title': '英雄篇', 'mode': 1, 'accuracy': 93.33}, {'title': '复兴篇', 'mode': 1, 'accuracy': 0}, {'title': '创新篇', 'mode': 1, 'accuracy': 0}, {'title': '信念篇', 'mode': 1, 'accuracy': 0}], 'province_name': '河南省', 'name': '王浩博', 'phone': '+86 18749227786'}
2021-03-26 19:09:47-DEBUG-获取图片信息：[{'title': '英雄篇', 'mode': 1, 'accuracy': 93.33}, {'title': '复兴篇', 'mode': 1, 'accuracy': 0}, {'title': '创新篇', 'mode': 1, 'accuracy': 0}, {'title': '信念篇', 'mode': 1, 'accuracy': 0}]
2021-03-26 19:09:48-DEBUG-已实例化处理类
2021-03-26 19:09:48-DEBUG-已启动数据库连接
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d5 启用答题睡眠
2021-03-26 19:09:48-INFO-英雄篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d6 启用答题睡眠
2021-03-26 19:09:48-INFO-复兴篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d7 启用答题睡眠
2021-03-26 19:09:48-INFO-创新篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d8 启用答题睡眠
2021-03-26 19:09:48-INFO-信念篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d9 关闭答题睡眠
2021-03-26 19:09:48-INFO-限时赛 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51da 关闭答题睡眠
2021-03-26 19:09:48-INFO-正在处理第 1 次的 抢十赛
2021-03-26 19:09:51-DEBUG-获取题目数据：{'code': -99, 'msg': 'Sorry, server error!', 'status_code': 200}
2021-03-26 19:09:51-DEBUG-已关闭Session
2021-03-26 19:09:51-DEBUG-已关闭数据库连接
2021-03-26 19:09:51-DEBUG-已更新Token数据供下次使用

Traceback (most recent call last):
  File "main-gui.py", line 705, in start
    self.processor.start(tray=self.tray)
  File "main-gui.py", line 379, in start
    self.process(mode_id=key,sleep=sleepflag)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 367, in iter
    return fut.result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "main-gui.py", line 417, in process
    self.logger.error("服务器返回错误代码：%d，错误信息：%s" %(json_response["code"],json_response["message"]))
KeyError: 'message'

**Comment by BiiiGerrr** [comment]
2021-03-26 19:09:48-DEBUG-已实例化处理类
2021-03-26 19:09:48-DEBUG-已启动数据库连接
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d5 启用答题睡眠
2021-03-26 19:09:48-INFO-英雄篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d6 启用答题睡眠
2021-03-26 19:09:48-INFO-复兴篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d7 启用答题睡眠
2021-03-26 19:09:48-INFO-创新篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d8 启用答题睡眠
2021-03-26 19:09:48-INFO-信念篇 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51d9 关闭答题睡眠
2021-03-26 19:09:48-INFO-限时赛 已跳过
2021-03-26 19:09:48-DEBUG-key=5f71e934bcdbf3a8c3ba51da 关闭答题睡眠
2021-03-26 19:09:48-INFO-正在处理第 1 次的 抢十赛
2021-03-26 19:09:51-DEBUG-获取题目数据：{'code': -99, 'msg': 'Sorry, server error!', 'status_code': 200}
2021-03-26 19:09:51-DEBUG-已关闭Session
2021-03-26 19:09:51-DEBUG-已关闭数据库连接
2021-03-26 19:09:51-DEBUG-已更新Token数据供下次使用

Traceback (most recent call last):
  File "main-gui.py", line 705, in start
    self.processor.start(tray=self.tray)
  File "main-gui.py", line 379, in start
    self.process(mode_id=key,sleep=sleepflag)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 339, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 430, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 367, in iter
    return fut.result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\BiiiGerrr\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\BiiiGerrr\Anaconda3\lib\site-packages\tenacity\__init__.py", line 433, in __call__
    result = fn(*args, **kwargs)
  File "main-gui.py", line 417, in process
    self.logger.error("服务器返回错误代码：%d，错误信息：%s" %(json_response["code"],json_response["message"]))
KeyError: 'message'

**Comment by arenekosreal** [comment]
你的这个文件似乎不是最新的？试试从仓库里面重新下载一份最新的，就是4小时之前的那个

**Comment by BiiiGerrr** [comment]
尴尬，没看到刚更新的，解决了，感谢感谢
