### ISSUE TITLE
使用GUI版本运行报错

### ISSUE THREAD

**Issue by Fyx2002** [Upsetin/ChinaUniOnline#72]
# Bug报告

## 脚本类型
GUI

## 问题描述
运行报错

## Python版本
3.9.2

## Pip安装的软件包

beautifulsoup4  4.9.3
certifi         2020.12.5
chardet         4.0.0
cycler          0.10.0
idna            2.10
kiwisolver      1.3.1
matplotlib      3.3.4
numpy           1.20.1
Pillow          8.1.2
pip             21.0.1
pycryptodome    3.10.1
pyparsing       2.4.7
PyQt6           6.0.3
PyQt6-Qt6       6.0.2
PyQt6-sip       13.0.1
PySocks         1.7.1
python-dateutil 2.8.1
requests        2.25.1
setuptools      49.2.1
six             1.15.0
soupsieve       2.2
tenacity        7.0.0
urllib3         1.26.4

## 操作系统
windows 10 ltsc 64位

## 终端输出  

Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x00000000260A65E0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x00000000260A65E0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Image.__del__ at 0x00000000260C6EE0>
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread

## 日志文件

2021-03-26 21:02:11-INFO-使用网页OAuth登陆
2021-03-26 21:02:11-INFO-正在获取二维码
2021-03-26 21:02:11-ERROR-登陆出错
2021-03-26 21:02:11-INFO-使用存储的登陆信息完成登陆
2021-03-26 21:02:11-INFO-使用存储的UID完成登陆
2021-03-26 21:02:12-INFO-用户 王 来自 兰州石化职业技术学院，手机号 +86 
2021-03-26 21:02:13-INFO-已准备处理四史学习内容
2021-03-26 21:02:13-INFO-正在处理第 1 次的 英雄篇
2021-03-26 21:02:14-INFO-题目：1952年1月2日，志愿军烈士（    ）在朝鲜平安南道成川郡石田里，为抢救跌入冰窟的朝鲜少年崔莹而牺牲。图为这位烈士的照片。【出题：武汉大学】
2021-03-26 21:02:14-INFO-来自数据库的答案：['罗盛教']
2021-03-26 21:02:15-INFO-第 1 道题目成功

**Comment by arenekosreal** [comment]
可以在设置里面打开调试模式再发一下新的日志数据吗😂INFO等级的日志看不出问题在哪里

**Comment by Fyx2002** [comment]
2021-03-26 23:27:08-INFO-已准备处理四史学习内容
2021-03-26 23:27:08-DEBUG-已实例化四史处理类
2021-03-26 23:27:08-DEBUG-已启动数据库连接
2021-03-26 23:27:08-DEBUG-key=5f71e934bcdbf3a8c3ba51d5 启用答题睡眠
2021-03-26 23:27:08-INFO-正在处理第 1 次的 英雄篇
2021-03-26 23:27:09-DEBUG-获取题目数据：{'code': 0, 'race_code': '605dfce4ca95da2100cc95e6', 'prev_qid': '5f71e934bcdbf3a8c3ba530b', 'question_ids': ['5f71e934bc5bf3a8c3bad30b', '5f71ef356d5fe02504ba6e75', '5f98496399c22ad36b0fc9bd', '59f8496796c22ad39b0fd8b3', '5f98e96296c22ad39b0fc548', '5f98a96496c224d39b0fccb1', '5498f96496c22ad39b0fcca8', '5f98496c96c22ad39b0f4c8d', '5f7ae934bcdbf3a8c3b154e1', '5f71ef3a5d6fea2504b07e50', '5f98496296c22ac39b0fd519', '5f98495e96c22ad39b0fb8a6', '5f7bef3a5d6fe02504ba7189', '5fb8495c96c22ad39b0f9063', '5f98b95c96c22ad3940fae59', '5f984963d6c22a939b0fcbd0', '5f98496296122ad39b0fc8c6', '5f71ef425d64e02504ba9f44', '5f71ef405d4fe02504ba906a', '5f98496526c29ad39b0fd3c2'], 'answers': {}, 'start_dt': '2021-03-26 23:25:24', 'opponent': {}, 'myself': {'id': '5fdb4ea0d8a4322857e4d88c', 'name': '董蕾', 'univ_id': '5b88f6d798234d3ae8d847fa', 'univ_name': '兰州石化职业技术学院', 'province_code': '620000', 'province_name': '甘肃省'}, 'time_limit': 600, 'server_dt': '2021-03-26 23:27:03.989563', 'mode_id': '5f71e934bcdbf3a8c3ba51d5', 'mode_title': '英雄篇', 'mode': 1, 'status_code': 200}
2021-03-26 23:27:09-DEBUG-生成验证码：rY3m
2021-03-26 23:27:09-DEBUG-选中需要模拟验证的位置：8
2021-03-26 23:27:12-DEBUG-获取选项信息：{'code': 0, 'data': {'id': '5f71e934bc5bf3a8c3bad30b', 'title': '<u style="text-decoration:none;"><nav style="display: inline;"><i style="font-style: normal;"><strong style="font-weight: normal;">图片为毛泽东主席将一级解放勋章授予<nav style="display:none;">骨恶死盈偷</nav></strong></i></nav></u><font><i style="font-style: normal;"><div style="display: inline;">中国人民解放军第一位女将军。这位女将军是（    ）。【出题：武汉大学】<strong style="font-weight: normal;display:none;">具闯覆峻琪！深育</strong></div></i></font>', 'category': 1, 'content': None, 'source': None, 'options': [{'id': '5fa1e934bcdbf3a8c3b75313', 'code': 'D', 'title': '<font><strong style="font-weight: normal;"><nav style="display: inline;">李希楷<span style="display:none;">脖挺滦混欢</span></nav></strong></font>', 'weight': 4.0}, {'id': '5d71e934bcfbf3a8c3ba5310', 'code': 'A', 'title': '<div style="display: inline;"><i style="font-style: normal;"><b style="font-weight: normal;"><strong style="font-weight: normal;"><u style="text-decoration:none;">乔佩<b style="display:none;">榔令些刻当濒铃彬</b></u></strong></b></i></div><i style="font-style: normal;"><strong style="font-weight: normal;"><span><u style="text-decoration:none;">娟<font style="display:none;">束盆县押隆星</font></u></span></strong></i><u style="text-decoration:none;"><span><div style="display: inline;"><div style="display: inline;"><u style="text-decoration:none;"> <nav style="display:none;">逐</nav></u></div></div></span></u>', 'weight': 1.0}, {'id': '5f71e394bcdbf3a8c3ba5312', 'code': 'C', 'title': '<font><nav style="display: inline;"><div style="display: inline;"><nav style="display: inline;">赵织雯 <nav style="display:none;">雷袁组赶扬</nav></nav></div></nav></font>', 'weight': 3.0}, {'id': '5f71e934bcfbd3a8c3ba5311', 'code': 'B', 'title': '<i style="font-style: normal;"><i style="font-style: normal;"><u style="text-decoration:none;"><span><div style="display: inline;">李贞<nav style="display:none;">晓插猛</nav></div></span></u></i></i>', 'weight': 2.0}], 'media_id': '5f68a2c0396beeb9929a92d7', 'media_content_type': 'application/octet-stream', 'media_location': 'https://univs-sishi-1256833609.cos.ap-beijing.myqcloud.com/HEPE3/images/2020/09/21/16006928656989641.png'}, 'status_code': 200}
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 3 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-获取选项信息：{'5fa1e934bcdbf3a8c3b75313': '李希楷', '5d71e934bcfbf3a8c3ba5310': '乔佩娟', '5f71e394bcdbf3a8c3ba5312': '赵织雯', '5f71e934bcfbd3a8c3ba5311': '李贞'}
2021-03-26 23:27:12-DEBUG-共清理 2 个干扰元素
2021-03-26 23:27:12-INFO-题目：图片为毛泽东主席将一级解放勋章授予中国人民解放军第一位女将军。这位女将军是（    ）。【出题：武汉大学】
2021-03-26 23:27:12-DEBUG-选择项目：{'5fa1e934bcdbf3a8c3b75313': '李希楷', '5d71e934bcfbf3a8c3ba5310': '乔佩娟', '5f71e394bcdbf3a8c3ba5312': '赵织雯', '5f71e934bcfbd3a8c3ba5311': '李贞'}
2021-03-26 23:27:12-INFO-来自数据库的答案：['李贞']
2021-03-26 23:27:12-DEBUG-正确答案的ID列表：['5f71e934bcfbd3a8c3ba5311']
2021-03-26 23:27:12-DEBUG-data={'activity_id': '5f71e934bcdbf3a8c3ba5061', 'question_id': '5f71e934bc5bf3a8c3bad30b', 'answer': ['5f71e934bcfbd3a8c3ba5311'], 'mode_id': '5f71e934bcdbf3a8c3ba51d5', 'way': 1}
2021-03-26 23:27:14-DEBUG-submit_response={'code': 0, 'data': {'correct': True, 'finished': False, 'reason': None, 'correct_ids': ['5f71e934bcfbd3a8c3ba5311']}, 'status_code': 200}
2021-03-26 23:27:14-INFO-第 1 道题目成功
2021-03-26 23:27:16-DEBUG-获取选项信息：{'code': 0, 'data': {'id': '5f71ef356d5fe02504ba6e75', 'title': '<i style="font-style: normal;"><strong style="font-weight: normal;"><u style="text-decoration:none;"><div style="display: inline;"><strong style="font-weight: normal;">中国早期信仰马<font style="display:none;">勤营其儆肺馆《彪</font></strong></div></u></strong></i><b style="font-weight: normal;"><div style="display: inline;">克思主义的人物，原中国同盟会会员、辛亥革命时期的活动家，其代表是<nav style="display:none;">除收幼友渐滨蓬</nav></div></b><u style="text-decoration:none;"><u style="text-decoration:none;"><b style="font-weight: normal;">（    ）。【<b style="display:none;">眩</b></b></u></u><i style="font-style: normal;"><b style="font-weight: normal;">出题：武汉大学】<div style="display: none;">攻狡升抛早门答吨</div></b></i>', 'category': 1, 'content': None, 'source': None, 'options': [{'id': '5f71ef465b6fe02504dacca5', 'code': '4', 'title': '<div style="display: inline;"><div style="display: inline;"><strong style="font-weight: normal;"><nav style="display: inline;"><strong style="font-weight: normal;">李<nav style="display:none;">咽膺控记神丙阐6</nav></strong></nav></strong></div></div><font><i style="font-style: normal;"><u style="text-decoration:none;">大钊<font style="display:none;">竞递审</font></u></i></font>', 'weight': 3.0}, {'id': '5f71ef46bd6fe025045acca3', 'code': '2', 'title': '<i style="font-style: normal;"><nav style="display: inline;"><font><b style="font-weight: normal;">陈独秀<font style="display:none;">俱肯萨携/昂孤淠</font></b></font></nav></i>', 'weight': 1.0}, {'id': '5f71ef465d6fe02504bacca4', 'code': '3', 'title': '<nav style="display: inline;"><u style="text-decoration:none;"><span>董<div style="display: none;">蔡吓给晰吭贞</div></span></u></nav><u style="text-decoration:none;"><b style="font-weight: normal;">必武<div style="display: none;">伸嫌碑R贴</div></b></u><u style="text-decoration:none;"><strong style="font-weight: normal;">\t<span style="display:none;">绵检峙融树</span></strong></u>', 'weight': 2.0}, {'id': '6f71ef465d5fe02504bacca2', 'code': '1', 'title': '<nav style="display: inline;"><u style="text-decoration:none;"><i style="font-style: normal;"><font><span>李汉俊<u style="display:none;text-decoration:none;">剥祸尺</u></span></font></i></u></nav>', 'weight': 0.0}]}, 'status_code': 200}
2021-03-26 23:27:16-DEBUG-共清理 2 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 3 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:16-DEBUG-获取选项信息：{'5f71ef465b6fe02504dacca5': '李大钊', '5f71ef46bd6fe025045acca3': '陈独秀', '5f71ef465d6fe02504bacca4': '董必武', '6f71ef465d5fe02504bacca2': '李汉俊'}

**Comment by Fyx2002** [comment]
2021-03-26 23:27:09-DEBUG-生成验证码：rY3m
2021-03-26 23:27:09-DEBUG-选中需要模拟验证的位置：8
2021-03-26 23:27:12-DEBUG-获取选项信息：{'code': 0, 'data': {'id': '5f71e934bc5bf3a8c3bad30b', 'title': '<u style="text-decoration:none;"><nav style="display: inline;"><i style="font-style: normal;"><strong style="font-weight: normal;">图片为毛泽东主席将一级解放勋章授予<nav style="display:none;">骨恶死盈偷</nav></strong></i></nav></u><font><i style="font-style: normal;"><div style="display: inline;">中国人民解放军第一位女将军。这位女将军是（    ）。【出题：武汉大学】<strong style="font-weight: normal;display:none;">具闯覆峻琪！深育</strong></div></i></font>', 'category': 1, 'content': None, 'source': None, 'options': [{'id': '5fa1e934bcdbf3a8c3b75313', 'code': 'D', 'title': '<font><strong style="font-weight: normal;"><nav style="display: inline;">李希楷<span style="display:none;">脖挺滦混欢</span></nav></strong></font>', 'weight': 4.0}, {'id': '5d71e934bcfbf3a8c3ba5310', 'code': 'A', 'title': '<div style="display: inline;"><i style="font-style: normal;"><b style="font-weight: normal;"><strong style="font-weight: normal;"><u style="text-decoration:none;">乔佩<b style="display:none;">榔令些刻当濒铃彬</b></u></strong></b></i></div><i style="font-style: normal;"><strong style="font-weight: normal;"><span><u style="text-decoration:none;">娟<font style="display:none;">束盆县押隆星</font></u></span></strong></i><u style="text-decoration:none;"><span><div style="display: inline;"><div style="display: inline;"><u style="text-decoration:none;"> <nav style="display:none;">逐</nav></u></div></div></span></u>', 'weight': 1.0}, {'id': '5f71e394bcdbf3a8c3ba5312', 'code': 'C', 'title': '<font><nav style="display: inline;"><div style="display: inline;"><nav style="display: inline;">赵织雯 <nav style="display:none;">雷袁组赶扬</nav></nav></div></nav></font>', 'weight': 3.0}, {'id': '5f71e934bcfbd3a8c3ba5311', 'code': 'B', 'title': '<i style="font-style: normal;"><i style="font-style: normal;"><u style="text-decoration:none;"><span><div style="display: inline;">李贞<nav style="display:none;">晓插猛</nav></div></span></u></i></i>', 'weight': 2.0}], 'media_id': '5f68a2c0396beeb9929a92d7', 'media_content_type': 'application/octet-stream', 'media_location': 'https://univs-sishi-1256833609.cos.ap-beijing.myqcloud.com/HEPE3/images/2020/09/21/16006928656989641.png'}, 'status_code': 200}
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 3 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:12-DEBUG-获取选项信息：{'5fa1e934bcdbf3a8c3b75313': '李希楷', '5d71e934bcfbf3a8c3ba5310': '乔佩娟', '5f71e394bcdbf3a8c3ba5312': '赵织雯', '5f71e934bcfbd3a8c3ba5311': '李贞'}
2021-03-26 23:27:12-DEBUG-共清理 2 个干扰元素
2021-03-26 23:27:12-INFO-题目：图片为毛泽东主席将一级解放勋章授予中国人民解放军第一位女将军。这位女将军是（    ）。【出题：武汉大学】
2021-03-26 23:27:12-DEBUG-选择项目：{'5fa1e934bcdbf3a8c3b75313': '李希楷', '5d71e934bcfbf3a8c3ba5310': '乔佩娟', '5f71e394bcdbf3a8c3ba5312': '赵织雯', '5f71e934bcfbd3a8c3ba5311': '李贞'}
2021-03-26 23:27:12-INFO-来自数据库的答案：['李贞']
2021-03-26 23:27:12-DEBUG-正确答案的ID列表：['5f71e934bcfbd3a8c3ba5311']
2021-03-26 23:27:12-DEBUG-data={'activity_id': '5f71e934bcdbf3a8c3ba5061', 'question_id': '5f71e934bc5bf3a8c3bad30b', 'answer': ['5f71e934bcfbd3a8c3ba5311'], 'mode_id': '5f71e934bcdbf3a8c3ba51d5', 'way': 1}
2021-03-26 23:27:14-DEBUG-submit_response={'code': 0, 'data': {'correct': True, 'finished': False, 'reason': None, 'correct_ids': ['5f71e934bcfbd3a8c3ba5311']}, 'status_code': 200}
2021-03-26 23:27:14-INFO-第 1 道题目成功
2021-03-26 23:27:16-DEBUG-获取选项信息：{'code': 0, 'data': {'id': '5f71ef356d5fe02504ba6e75', 'title': '<i style="font-style: normal;"><strong style="font-weight: normal;"><u style="text-decoration:none;"><div style="display: inline;"><strong style="font-weight: normal;">中国早期信仰马<font style="display:none;">勤营其儆肺馆《彪</font></strong></div></u></strong></i><b style="font-weight: normal;"><div style="display: inline;">克思主义的人物，原中国同盟会会员、辛亥革命时期的活动家，其代表是<nav style="display:none;">除收幼友渐滨蓬</nav></div></b><u style="text-decoration:none;"><u style="text-decoration:none;"><b style="font-weight: normal;">（    ）。【<b style="display:none;">眩</b></b></u></u><i style="font-style: normal;"><b style="font-weight: normal;">出题：武汉大学】<div style="display: none;">攻狡升抛早门答吨</div></b></i>', 'category': 1, 'content': None, 'source': None, 'options': [{'id': '5f71ef465b6fe02504dacca5', 'code': '4', 'title': '<div style="display: inline;"><div style="display: inline;"><strong style="font-weight: normal;"><nav style="display: inline;"><strong style="font-weight: normal;">李<nav style="display:none;">咽膺控记神丙阐6</nav></strong></nav></strong></div></div><font><i style="font-style: normal;"><u style="text-decoration:none;">大钊<font style="display:none;">竞递审</font></u></i></font>', 'weight': 3.0}, {'id': '5f71ef46bd6fe025045acca3', 'code': '2', 'title': '<i style="font-style: normal;"><nav style="display: inline;"><font><b style="font-weight: normal;">陈独秀<font style="display:none;">俱肯萨携/昂孤淠</font></b></font></nav></i>', 'weight': 1.0}, {'id': '5f71ef465d6fe02504bacca4', 'code': '3', 'title': '<nav style="display: inline;"><u style="text-decoration:none;"><span>董<div style="display: none;">蔡吓给晰吭贞</div></span></u></nav><u style="text-decoration:none;"><b style="font-weight: normal;">必武<div style="display: none;">伸嫌碑R贴</div></b></u><u style="text-decoration:none;"><strong style="font-weight: normal;">\t<span style="display:none;">绵检峙融树</span></strong></u>', 'weight': 2.0}, {'id': '6f71ef465d5fe02504bacca2', 'code': '1', 'title': '<nav style="display: inline;"><u style="text-decoration:none;"><i style="font-style: normal;"><font><span>李汉俊<u style="display:none;text-decoration:none;">剥祸尺</u></span></font></i></u></nav>', 'weight': 0.0}]}, 'status_code': 200}
2021-03-26 23:27:16-DEBUG-共清理 2 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 3 个干扰元素
2021-03-26 23:27:16-DEBUG-共清理 1 个干扰元素
2021-03-26 23:27:16-DEBUG-获取选项信息：{'5f71ef465b6fe02504dacca5': '李大钊', '5f71ef46bd6fe025045acca3': '陈独秀', '5f71ef465d6fe02504bacca4': '董必武', '6f71ef465d5fe02504bacca2': '李汉俊'}

**Comment by arenekosreal** [comment]
这似乎是matplotlib默认绘图后端的问题，请在脚本最开始加上
```python
from matplotlib import use
use("Agg")
```
试一下问题是否解决
这倒是一个挺玄学的问题，我这里也是使用默认的TkAgg后端，却没有这个问题
如果问题解决，请点一下Close issue关闭这一个问题，我将在以后的版本里面把绘图后端切换到Agg

**Comment by Fyx2002** [comment]
保存数据库也是失败的,
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record
QSqlQuery::value: not positioned on a valid record

**Comment by arenekosreal** [comment]
脚本是最新的那个吗？就是2小时以前那个。我这里已经解决了这个警告

**Comment by arenekosreal** [comment]
如果问题已经解决，请点一下Close issue关闭这个问题

**Comment by Fyx2002** [comment]
OK,已解决
