### ISSUE TITLE
抢十赛问题

### ISSUE THREAD

**Issue by BiiiGerrr** [Upsetin/ChinaUniOnline#93]
抢十赛进入第二次的时候会出错
Traceback (most recent call last):
  File "main-gui2.py", line 882, in start
    update_info_signal=self.update_info_signal, prefix="dsjd")
  File "main-gui2.py", line 226, in __init__
    self.login()
  File "main-gui2.py", line 268, in login
    self.login(type_="v0")
  File "main-gui2.py", line 396, in login
    name = json_response["data"]["name"]
KeyError: 'data'

第一次答对十道题停止后，第二次会报错

2021-04-08 14:20:55-INFO-抢十赛数目已达到10，正在终止答题
2021-04-08 14:20:57-INFO-执行完成，正确数：10，答题用时：19 秒
2021-04-08 14:20:57-INFO-处于对战模式，对方信息：来自 浙江邮电职业技术学院 的 李芳，正确数 10，用时 147秒
2021-04-08 14:20:58-INFO-此次成功查询 10 个题，收录 0 个题
2021-04-08 14:20:58-INFO-全部项目已完成处理
2021-04-08 14:20:58-INFO-使用网页OAuth登陆
2021-04-08 14:20:58-INFO-正在获取二维码
2021-04-08 14:20:58-ERROR-登陆出错
2021-04-08 14:20:58-INFO-使用存储的登陆信息完成登陆
2021-04-08 14:20:58-INFO-使用存储的UID完成登陆

**Comment by arenekosreal** [comment]
日志里面那个登陆出错是因为网页登陆被服务器关闭了，是正常现象。单从错误追踪看不出问题是什么，麻烦发一下打开调试模式后的日志。不过我这里反复刷都没有出现这个问题，不确定是不是网络因素，因为最近四史服务器相当不稳定，刷题速度都很慢

**Comment by BiiiGerrr** [comment]
2021-04-08 15:27:28-DEBUG-第 1 次执行成功
2021-04-08 15:27:28-DEBUG-已更新处理列表
2021-04-08 15:27:28-DEBUG-项目 抢十赛 已完成，正在从列表中移除
2021-04-08 15:27:28-INFO-全部项目已完成处理
2021-04-08 15:27:28-DEBUG-已关闭Session
2021-04-08 15:27:28-DEBUG-获取图片信息：[{'title': '英雄篇', 'mode': 1, 'accuracy': 84.17}, {'title': '复兴篇', 'mode': 1, 'accuracy': 0}, {'title': '创新篇', 'mode': 1, 'accuracy': 0}, {'title': '信念篇', 'mode': 1, 'accuracy': 0}]
2021-04-08 15:27:28-DEBUG-已更新Token数据供下次使用
2021-04-08 15:27:28-INFO-使用网页OAuth登陆
2021-04-08 15:27:28-DEBUG-random=y3fqA876x9i2YT5wSZUR
2021-04-08 15:27:28-INFO-正在获取二维码
2021-04-08 15:27:29-DEBUG-response={'data': None, 'code': 500, 'message': '获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。'}
2021-04-08 15:27:29-ERROR-登陆出错
2021-04-08 15:27:29-DEBUG-获取qrcode地址失败，请确认已打开小程序OAuth。若已打开，可能是网络问题，请重试。
2021-04-08 15:27:29-INFO-使用存储的登陆信息完成登陆
2021-04-08 15:27:29-DEBUG-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTc4NzY5NzcsImlhdCI6MTYxNzg2NjE3NywiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNzg2NjE3NywidWlkIjoiNjA1MjMyYzkyYjI5NjIzYzdjMTgwZTE3IiwibmFtZSI6Ilx1NzM4Ylx1NmQ2OVx1NTM1YSIsImNvZGUiOiI2MDUyMzJjOTJiMjk2MjNjN2MxODBlMTciLCJpc19wZXJmZWN0Ijp0cnVlfQ.8KbM4YvCZ5A7auarK-b0daaNCSMrkrGO3USthUWR2Nw,refresh_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTc4ODc3NzcsImlhdCI6MTYxNzg2NjE3NywiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNzg2NjE3NywidWlkIjoiNjA1MjMyYzkyYjI5NjIzYzdjMTgwZTE3IiwibmFtZSI6Ilx1NzM4Ylx1NmQ2OVx1NTM1YSIsImlzX3BlcmZlY3QiOnRydWV9.Q5FGa7TUsh542x2tzp9hWi03QxvzLK1r7l-TaKVMi5Q,uid=605232c92b29623c7c180e17
2021-04-08 15:27:29-INFO-使用存储的UID完成登陆
2021-04-08 15:27:29-DEBUG-Token分片：eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
2021-04-08 15:27:29-DEBUG-分片解码完成
2021-04-08 15:27:29-DEBUG-Token分片：eyJleHAiOjE2MTc4Nzc3MDEsImlhdCI6MTYxNzg2NjkwMSwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNzg2NjkwMSwidWlkIjoiNjA1MjMyYzkyYjI5NjIzYzdjMTgwZTE3IiwibmFtZSI6Ilx1NjViMFx1NzUyOFx1NjIzNyIsImNvZGUiOiI2MDUyMzJjOTJiMjk2MjNjN2MxODBlMTciLCJpc19wZXJmZWN0IjpmYWxzZX0
2021-04-08 15:27:29-DEBUG-分片解码完成
2021-04-08 15:27:29-DEBUG-Token分片：AGgzumuZ_DUdBpto4FqN1S3yexdPZlPkq6QBSg1_H0Y
2021-04-08 15:27:29-DEBUG-跳过分片解码
2021-04-08 15:27:29-DEBUG-获取用户信息：{'code': -99, 'msg': 'Sorry, server error!', 'status_code': 200}

**Comment by arenekosreal** [comment]
最后一行看出来了，服务器返回的信息说服务器炸了，考虑到我这里倒没有什么问题，估计是网络原因
