### ISSUE TITLE
看起来获取不到question_ids？

### ISSUE THREAD

**Issue by ghost** [Upsetin/ChinaUniOnline#95]
# Bug报告

## 脚本类型

[^_^]:使用的是原版还是GUI版本  
原版

## 问题描述

[^_^]:遇到了什么问题
运行后报错：
```zsh
英雄篇-正在第1次刷题～
Traceback (most recent call last):
  File "main.py", line 485, in <module>
    GetQuestions()
  File "main.py", line 107, in GetQuestions
    question_ids = response.json()['question_ids']
KeyError: 'question_ids'
```
## Python版本

[^_^]:正在使用的Python版本及架构
Python 3.8.2 (default, Dec 21 2020, 15:06:04) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

## Pip安装的软件包

```text
 Package    Version  
---------- ---------
certifi    2020.12.5
chardet    4.0.0    
idna       2.10     
pip        19.2.3   
requests   2.25.1   
setuptools 41.2.0   
six        1.15.0   
urllib3    1.26.4   
wheel      0.33.1  
```

## 操作系统

[^_^]:是Windows还是Linux或者OSX以及是32位系统还是64位系统
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91
Darwin SeatiadeMacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

## 终端输出  

```shell

seatia@SeatiadeMacBook-Air ChinaUniOnline-main-2 % python3 main.py
请输入uid或者token「不含Bearer，即后面那一串内容.」
输入完成后回车:（我的uid）
正在获取token，请稍后...
token已更新...
欢迎你，来自xxxxx的xxxxx,当前积分:xxxx
暂只适配英雄篇,请输入的刷题次数 (55次稳上1000分,积分更新有延迟，不用担心!): 44

当前积分: xxxx

英雄篇-正在第1次刷题～
Traceback (most recent call last):
  File "main.py", line 485, in <module>
    GetQuestions()
  File "main.py", line 107, in GetQuestions
    question_ids = response.json()['question_ids']
KeyError: 'question_ids'

```

## 日志文件

```text

在这里粘贴调试模式（设置里面打开）日志文件内容，替换这一行文字


```

**Comment by arenekosreal** [comment]
这几天服务器抽风，经常拿不到数据，等一下重试就好了

**Comment by ghost** [comment]
> 这几天服务器抽风，经常拿不到数据，等一下重试就好了

ok

**Comment by Leonisux** [comment]
我一直都是这个问题怎么办，试了好多次都是key error ：“question_ids”

**Comment by arenekosreal** [comment]
> 我一直都是这个问题怎么办，试了好多次都是key error ：“question_ids”

具体终端输出是啥？如果是用的可执行程序，麻烦手动配置python并使用python运行脚本，这样才会有错误追踪

**Comment by Leonisux** [comment]
> > 我一直都是这个问题怎么办，试了好多次都是key error ：“question_ids”
> 
> 具体终端输出是啥？如果是用的可执行程序，麻烦手动配置python并使用python运行脚本，这样才会有错误追踪
Traceback (most recent call last):
  File "main.py", line 485, in <module>
    GetQuestions()
  File "main.py", line 107, in GetQuestions
    question_ids = response.json()['question_ids']
KeyError: 'question_ids'

**Comment by arenekosreal** [comment]
麻烦把脚本106行的注释符号去掉，看看获得的详细题目信息是啥

**Comment by Leonisux** [comment]
> 麻烦把脚本106行的注释符号去掉，看看获得的详细题目信息是啥
获取题目: {'code': 4832, 'msg': 'Greater than the join threshold.', 'status_code': 200}

**Comment by arenekosreal** [comment]
> > 麻烦把脚本106行的注释符号去掉，看看获得的详细题目信息是啥
> > 获取题目: {'code': 4832, 'msg': 'Greater than the join threshold.', 'status_code': 200}

这是由于答题次数过多导致的，所以只有等服务器啥时候不认为你答题次数过多再来，具体要等多久我这里也没有一个固定的时间。。。

**Comment by Leonisux** [comment]
> > > 麻烦把脚本106行的注释符号去掉，看看获得的详细题目信息是啥
> > > 获取题目: {'code': 4832, 'msg': 'Greater than the join threshold.', 'status_code': 200}
> 
> 这是由于答题次数过多导致的，所以只有等服务器啥时候不认为你答题次数过多再来，具体要等多久我这里也没有一个固定的时间。。。

好的吧
